### ISSUE TITLE
funcs wont toggle

### ISSUE THREAD

**Issue by omegabr99** [UnkwUsr/hlhax#1]
Hello I've tried to enable aimbot but it would return "invalid command" on the console

**Comment by omegabr99** [comment]
i have another issue uhh aimbot doesnt work like idk how to make it aim

**Comment by UnkwUsr** [comment]
Are you even sure hax loaded fine? Check out newly added step in readme:

> 7. Make sure hax loaded fine.
>
> Check in-game console and find line "Hack loaded FINE". Also you can try to start typing `hx_` or `cv_` and a completion list should appear.

**Comment by UnkwUsr** [comment]
Also, can you provide please exactly command that you've tried to enable aimbot?

Anyway, firstly you should bind key for auto aim: `bind f +hx_aimbot`. When you'll press this key, your crosshair will stick to the target. Then you can enable auto attack, so when your crosshair sticked on the target, you'll automatically start shooting: `cv_aimbot_attack_auto 1`. And, sadly, at the moment aimbot (and sometimes wallhack functions) does not work on all servers.

**Comment by omegabr99** [comment]
> Also, can you provide please exactly command that you've tried to enable aimbot?
> 
> Anyway, firstly you should bind key for auto aim: `bind f +hx_aimbot`. When you'll press this key, your crosshair will stick to the target. Then you can enable auto attack, so when your crosshair sticked on the target, you'll automatically start shooting: `cv_aimbot_attack_auto 1`. And, sadly, at the moment aimbot (and sometimes wallhack functions) does not work on all servers.

ah i see,do i have to do the same for the other functions?

**Comment by UnkwUsr** [comment]
Can't say exactly. What other functions are you interested in?

Also you can check code, I tried to keep all stuff related to one function in one file.

**Comment by omegabr99** [comment]
> Can't say exactly. What other functions are you interested in?
> 
> Also you can check code, I tried to keep all stuff related to one function in one file.

sgs_Bhop

**Comment by UnkwUsr** [comment]
Ah, it just add funny jump animation when you actually doing sgs:

https://user-images.githubusercontent.com/49063932/159188237-5dfec911-d93d-461b-8d2a-2f54680f28b0.mp4

(also in this video was used `cv_thirdperson 1`)

And if you look for real bhop: sadly, there is not such function yet, because I've used openag mod where bhop is builtin.
