### ISSUE TITLE
Doesn't work on Steam version anymore

### ISSUE THREAD

**Issue by liberteryen** [UnkwUsr/hlhax#8]
It no longer works in the current version of Counter Strike on Steam. When you select and install "steam_legacy" from the betas section, it only starts when you are dead, the cheat does not work when you are alive in the game. Is there a solution?

**Comment by 8dcc** [comment]
First part of this repo's readme:

> Fortunetly broken after Half-Life 25th anniversary update (because binaries do not export dynamic symbols now). I'm not going to fix this because:
>   1. I hope hl1 will get some activity again, so I don't want to flood servers with cheaters.
>   2. I don't see much fun in dealing with byte patterns and offsets.

See also https://github.com/8dcc/hl-cheat/issues/5

**Comment by liberteryen** [comment]
I get it, it's my fault for not reading the read me file. I am sorry. I hope a solution is found as soon as possible.

**Comment by liberteryen** [comment]
Be aware, if you install condition zero from the beta section with steam legacy, the cheat still works.

im using google translate

**Comment by liberteryen** [comment]
![resim](https://github.com/UnkwUsr/hlhax/assets/84645312/76b797be-9acb-443f-befd-c9b2b6bf6d13)

**Comment by 8dcc** [comment]
You can also use it in Half-Life 1 if you enable the beta from the steam settings.

![image](https://github.com/UnkwUsr/hlhax/assets/29655971/d658e754-4222-4bd1-a9e9-23c5b9c581d4)
